name: CI/CD for Churn Prediction

on:
  push:
    branches:
      - main
    paths:
      - train.py
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
     
      - name: Build Docker Image
        run: |
          docker build -t xavier-test .

      - name: Run Tests in Docker
        run: |
          docker run --rm xavier-test python -m pytest -q

      
